### ISSUE TITLE
Softdevice header files path is wrong on makefile

### ISSUE THREAD

**Issue by ASL07** [RAKWireless/RUI_Platform_Firmware_GCC#1]
When executing the make command I get
Makefile:361: Cannot find include folder: ../../components/softdevice/s132/headers/nRF52

The name of the directory is wrong , it should be  ../../components/softdevice/s132/headers/nrf52

I am using Mac OS and have downloaded both RUI and SDK from your github

**Comment by RAKWireless** [comment]
Thanks for pointing out the problem. I test in win 10, and no error. I will change to lower case.
